version: '3.9'

services:
  stroytrend.webapp:
    image: gr1mez/stroytrend
    build:
      context: .
      dockerfile: StroyTrend.WebApp/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"